import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { formatFirstName, formatLastName } from "@/lib/formatName";

// ClubMember now only contains identity fields (seasonal fields are in membership_yearly_status)
export interface ClubMember {
  id: string;
  member_id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  birth_date: string | null;
  address: string | null;
  joined_at: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  gender: string | null;
  notes: string | null;
  departure_date: string | null;
  created_at: string;
  updated_at: string;
}

export interface ClubMemberInsert {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  birth_date?: string | null;
  address?: string | null;
  joined_at?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  gender?: string | null;
  notes?: string | null;
}

export interface RegisteredEmail {
  email: string;
  avatar_url: string | null;
}

export const useClubMembersDirectory = () => {
  const queryClient = useQueryClient();

  // Fetch all club members
  const { data: members, isLoading, error } = useQuery({
    queryKey: ["club-members-directory"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("club_members_directory")
        .select("*")
        .order("last_name", { ascending: true });

      if (error) throw error;
      return data as ClubMember[];
    },
  });

  // Fetch registered profile emails for sync status
  const { data: registeredProfiles } = useQuery({
    queryKey: ["registered-emails"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("profiles")
        .select("email, avatar_url");

      if (error) throw error;
      return (data as RegisteredEmail[]).map(p => ({
        email: p.email.toLowerCase(),
        avatar_url: p.avatar_url,
      }));
    },
  });
  const registeredEmails = registeredProfiles?.map(p => p.email);

  // Create member
  const createMember = useMutation({
    mutationFn: async (member: ClubMemberInsert) => {
      const { data, error } = await supabase
        .from("club_members_directory")
        .insert({
          first_name: formatFirstName(member.first_name),
          last_name: formatLastName(member.last_name),
          email: member.email,
          phone: member.phone,
          birth_date: member.birth_date,
          address: member.address,
          joined_at: member.joined_at,
          emergency_contact_name: member.emergency_contact_name,
          emergency_contact_phone: member.emergency_contact_phone,
          gender: member.gender,
          notes: member.notes,
          member_id: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
      toast.success("Adhérent ajouté avec succès");
    },
    onError: (error: Error) => {
      if (error.message.includes("duplicate key")) {
        toast.error("Un adhérent avec cet email existe déjà");
      } else {
        toast.error(error.message || "Erreur lors de l'ajout");
      }
    },
  });

  // Update member
  const updateMember = useMutation({
    mutationFn: async ({ id, ...updates }: Partial<ClubMember> & { id: string }) => {
      if (updates.first_name) updates.first_name = formatFirstName(updates.first_name);
      if (updates.last_name) updates.last_name = formatLastName(updates.last_name);
      const { data, error } = await supabase
        .from("club_members_directory")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
      toast.success("Adhérent mis à jour");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Erreur lors de la mise à jour");
    },
  });

  // Archive member (member left the club): record a departure date and cut
  // their app access, instead of physically deleting the row — deleting
  // cascaded to membership_yearly_status and lost cotisation/licence history.
  const archiveMember = useMutation({
    mutationFn: async ({ id, email, departureDate }: { id: string; email: string; departureDate: string }) => {
      const { error } = await supabase
        .from("club_members_directory")
        .update({ departure_date: departureDate })
        .eq("id", id);

      if (error) throw error;

      const { error: accessError } = await supabase.functions.invoke("archive-member-access", {
        body: { email },
      });
      if (accessError) throw accessError;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
      queryClient.invalidateQueries({ queryKey: ["membership-history"] });
      toast.success("Adhérent marqué comme parti, accès coupé");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Erreur lors de l'archivage");
    },
  });

  // Upsert member (for CSV import) - only identity fields
  const upsertMember = useMutation({
    mutationFn: async (member: ClubMemberInsert) => {
      // Check if email exists
      const { data: existing } = await supabase
        .from("club_members_directory")
        .select("id")
        .eq("email", member.email.toLowerCase())
        .maybeSingle();

      if (existing) {
        // Update existing
        const { data, error } = await supabase
          .from("club_members_directory")
          .update({
            first_name: formatFirstName(member.first_name),
            last_name: formatLastName(member.last_name),
            phone: member.phone,
            birth_date: member.birth_date,
            address: member.address,
            joined_at: member.joined_at,
            emergency_contact_name: member.emergency_contact_name,
            emergency_contact_phone: member.emergency_contact_phone,
            gender: member.gender,
            notes: member.notes,
          })
          .eq("id", existing.id)
          .select()
          .single();

        if (error) throw error;
        return { data, updated: true };
      } else {
        // Insert new
        const { data, error } = await supabase
          .from("club_members_directory")
          .insert({
            first_name: formatFirstName(member.first_name),
            last_name: formatLastName(member.last_name),
            email: member.email.toLowerCase(),
            phone: member.phone,
            birth_date: member.birth_date,
            address: member.address,
            joined_at: member.joined_at,
            emergency_contact_name: member.emergency_contact_name,
            emergency_contact_phone: member.emergency_contact_phone,
            gender: member.gender,
            notes: member.notes,
            member_id: "", // Will be auto-generated by trigger
          })
          .select()
          .single();

        if (error) throw error;
        return { data, updated: false };
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
    },
  });

  // Check if email is registered in the app
  const isEmailRegistered = (email: string): boolean => {
    return registeredEmails?.includes(email.toLowerCase()) ?? false;
  };

  // Registered in the app but no profile photo
  const hasProfilePhoto = (email: string): boolean => {
    const profile = registeredProfiles?.find(p => p.email === email.toLowerCase());
    return !!profile?.avatar_url;
  };

  return {
    members,
    isLoading,
    error,
    registeredEmails,
    createMember,
    updateMember,
    archiveMember,
    upsertMember,
    isEmailRegistered,
    hasProfilePhoto,
  };
};
