import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export interface ClubMember {
  id: string;
  member_id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  birth_date: string | null;
  address: string | null;
  apnea_level: string | null;
  joined_at: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  gender: string | null;
  notes: string | null;
  board_role: string | null;
  is_encadrant: boolean;
  created_at: string;
  updated_at: string;
}

export interface ClubMemberInsert {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  birth_date?: string | null;
  address?: string | null;
  apnea_level?: string | null;
  joined_at?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  gender?: string | null;
  notes?: string | null;
  board_role?: string | null;
  is_encadrant?: boolean;
}

export interface RegisteredEmail {
  email: string;
}

export const useClubMembersDirectory = () => {
  const queryClient = useQueryClient();

  // Fetch all club members
  const { data: members, isLoading, error } = useQuery({
    queryKey: ["club-members-directory"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("club_members_directory")
        .select("*")
        .order("last_name", { ascending: true });

      if (error) throw error;
      return data as ClubMember[];
    },
  });

  // Fetch registered profile emails for sync status
  const { data: registeredEmails } = useQuery({
    queryKey: ["registered-emails"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("profiles")
        .select("email");

      if (error) throw error;
      return (data as RegisteredEmail[]).map(p => p.email.toLowerCase());
    },
  });

  // Create member
  const createMember = useMutation({
    mutationFn: async (member: ClubMemberInsert) => {
      const { data, error } = await supabase
        .from("club_members_directory")
        .insert({
          first_name: member.first_name,
          last_name: member.last_name,
          email: member.email,
          phone: member.phone,
          birth_date: member.birth_date,
          address: member.address,
          apnea_level: member.apnea_level,
          joined_at: member.joined_at,
          emergency_contact_name: member.emergency_contact_name,
          emergency_contact_phone: member.emergency_contact_phone,
          gender: member.gender,
          notes: member.notes,
          board_role: member.board_role,
          is_encadrant: member.is_encadrant ?? false,
          member_id: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
      toast.success("Adhérent ajouté avec succès");
    },
    onError: (error: Error) => {
      if (error.message.includes("duplicate key")) {
        toast.error("Un adhérent avec cet email existe déjà");
      } else {
        toast.error(error.message || "Erreur lors de l'ajout");
      }
    },
  });

  // Update member
  const updateMember = useMutation({
    mutationFn: async ({ id, ...updates }: Partial<ClubMember> & { id: string }) => {
      const { data, error } = await supabase
        .from("club_members_directory")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
      toast.success("Adhérent mis à jour");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Erreur lors de la mise à jour");
    },
  });

  // Delete member
  const deleteMember = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("club_members_directory")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
      toast.success("Adhérent supprimé");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Erreur lors de la suppression");
    },
  });

  // Upsert member (for CSV import)
  const upsertMember = useMutation({
    mutationFn: async (member: ClubMemberInsert) => {
      // Check if email exists
      const { data: existing } = await supabase
        .from("club_members_directory")
        .select("id")
        .eq("email", member.email.toLowerCase())
        .maybeSingle();

      if (existing) {
        // Update existing
        const { data, error } = await supabase
          .from("club_members_directory")
          .update({
            first_name: member.first_name,
            last_name: member.last_name,
            phone: member.phone,
            birth_date: member.birth_date,
            address: member.address,
            apnea_level: member.apnea_level,
            joined_at: member.joined_at,
            emergency_contact_name: member.emergency_contact_name,
            emergency_contact_phone: member.emergency_contact_phone,
            gender: member.gender,
            notes: member.notes,
            board_role: member.board_role,
            is_encadrant: member.is_encadrant ?? false,
          })
          .eq("id", existing.id)
          .select()
          .single();

        if (error) throw error;
        return { data, updated: true };
      } else {
        // Insert new
        const { data, error } = await supabase
          .from("club_members_directory")
          .insert({
            first_name: member.first_name,
            last_name: member.last_name,
            email: member.email.toLowerCase(),
            phone: member.phone,
            birth_date: member.birth_date,
            address: member.address,
            apnea_level: member.apnea_level,
            joined_at: member.joined_at,
            emergency_contact_name: member.emergency_contact_name,
            emergency_contact_phone: member.emergency_contact_phone,
            gender: member.gender,
            notes: member.notes,
            board_role: member.board_role,
            is_encadrant: member.is_encadrant ?? false,
            member_id: "", // Will be auto-generated by trigger
          })
          .select()
          .single();

        if (error) throw error;
        return { data, updated: false };
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["club-members-directory"] });
    },
  });

  // Check if email is registered in the app
  const isEmailRegistered = (email: string): boolean => {
    return registeredEmails?.includes(email.toLowerCase()) ?? false;
  };

  return {
    members,
    isLoading,
    error,
    registeredEmails,
    createMember,
    updateMember,
    deleteMember,
    upsertMember,
    isEmailRegistered,
  };
};
